# Site settings
title: 享受工作 享受生活
email: icehong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  看看jekyll的blog系统好不好用, just for fun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://icehong.github.io" # the base hostname & protocol for your site
twitter_username: ieehong
github_username:  icehong

# Build settings
markdown: kramdown

host:        192.168.1.100
port:        4000